import React, { useState } from 'react';
import Comment from './Comment';
import './CommentModal.css';

/**
 * Post comment modal
 * 
 * @param {function} (prop) handleClose
 * @param {boolean} (prop) show
 * @param {object} (prop) comments
 * @param {function} (prop) setComments
 * @param {string} (prop) post_id  
 * @returns 
 */
function CommentModal({ handleClose, show, comments, setComments, post_id}) {
  // Conditional name of class
  const showHideClassName = show ? "modal display-block" : "modal display-none";

  // Post ID, generated by Reddit
  const id = "t3_" + post_id;

  // Response state
  const [state, setState] = useState({
    response: "",
  })

  /**
   * @summary Updates comment field
   * @param {object} event 
   */
  function updateResponse(event) {
    setState({
      ...state,
      response: event.target.value
    });
  }

  /**
   * @summary Fetches a POST request to proxy specifying input comment
   * @param {object} event 
   */
  function handleCommentPost(event) {
    event.preventDefault();

    // Send POST request to Reddit proxy
    fetch(`/api/comment?id=${encodeURIComponent(id)}&text=${encodeURIComponent(state.response)}`, {method: "POST"})
    .then(
        response => console.log(response)
    )

    // Add comment to UI
    const comment = <Comment key={0} content={{author: "You!", body: state.response}}/>
    setComments(prev_state => ({
      ...prev_state,
      comments: [...prev_state.comments, comment]
    }));

    // Clear comment response
    setState(prev_state => ({
      ...prev_state,
      response: ""
    }));
  }

  return (
    <div className={showHideClassName}>
      <section className="modal-main">
        <div className="comment_header">
          <h1 id="comment_title">Comments</h1>
          <button id="close_comments" type="button" onClick={handleClose}>X</button>
        </div>
        <div className="comment_section">
          {comments}
        </div>
        <div className="comment_response">
          <h1 id="response_title">Join the discussion!</h1>
          <form onSubmit={handleCommentPost}>
            <input
              id="comment_text"
              type="text"
              value={state.response}
              onChange={updateResponse}
            />
            <button type="submit">Post</button>
          </form>
        </div>
      </section>
    </div>
  );
};

export default CommentModal;